export class SocioEconomico {

    constructor(
        public IdBarrio?: string,
        public IdCalle?: string,
        public NroCalle?: number,
        public IdLocalidad?: string,
        public Vinculo?: string,
        public FechaNac?: string,
        public EstudiosCursados?: string,
        public IdEscuela?: string,
        public IdTipoCasa?: string,
        public Profesion?: string,
        public SituacionLaboral?: string,
        public ObraSocial?: string,
        public IdProblSocial?: string,
        public TipoDiscapacidad?: string,
        public IdVivienda?: string,
        public IdTipoVivienda?: string,
        public IdModulo?: string,
        public Habitaciones?: string,
        public IdTecho?: string,
        public IdPiso?: string,
        public IdBano?: string,
        public AguaCte?: string,
        public GasNatural?: string,
        public RedCloacal?: string,
        public ContratoGas?: string,
        public IdSituacionInmueble?: string,
        public IdLocalComercial?: string,
        public IdConstruccion?: string,
        public Observaciones?: string,
        public MetrosConstruccion?: string,
        public TipoRubro?: string,
        public NombreLocalComercial?: string,
        public NroLote?: string,
        public NroPadron?: string,
        public IdPersona?: number
    ) { }

}
